import { KpiData, DrugRow, ChartDataPoint, NavItem } from "./types";

export const navItems: NavItem[] = [
  { label: "Dashboard", key: "dashboard" },
  { label: "Insights", key: "insights" },
  { label: "Supply", key: "supply" },
  { label: "Settings", key: "settings" },
];

export const kpiData: KpiData[] = [
  {
    id: "active-pharmacies",
    label: "Active Pharmacies",
    value: "128",
    icon: "Building2",
    trend: 4.2,
    trendLabel: "vs last month",
  },
  {
    id: "drugs-monitored",
    label: "Drugs Monitored",
    value: "12,450",
    icon: "Pill",
    trend: 7.1,
    trendLabel: "vs last month",
  },
  {
    id: "cost-savings",
    label: "Cost Savings",
    value: "£3.2M",
    icon: "TrendingUp",
    trend: 12.5,
    trendLabel: "vs last quarter",
  },
  {
    id: "stock-alerts",
    label: "Stock Alerts Today",
    value: "47",
    icon: "AlertTriangle",
    trend: -8.3,
    trendLabel: "vs yesterday",
  },
];

export const drugTableData: DrugRow[] = [
  {
    id: "1",
    name: "Atorvastatin 40mg",
    manufacturer: "Pfizer Ltd",
    stockStatus: "In Stock",
    priceChange: 2.4,
    lastUpdated: "2026-03-17",
  },
  {
    id: "2",
    name: "Metformin 500mg",
    manufacturer: "Teva UK",
    stockStatus: "Low Stock",
    priceChange: -1.8,
    lastUpdated: "2026-03-17",
  },
  {
    id: "3",
    name: "Lisinopril 10mg",
    manufacturer: "AstraZeneca",
    stockStatus: "In Stock",
    priceChange: 0.6,
    lastUpdated: "2026-03-16",
  },
  {
    id: "4",
    name: "Omeprazole 20mg",
    manufacturer: "Sandoz",
    stockStatus: "Out of Stock",
    priceChange: -4.2,
    lastUpdated: "2026-03-15",
  },
  {
    id: "5",
    name: "Amoxicillin 500mg",
    manufacturer: "GSK Consumer",
    stockStatus: "In Stock",
    priceChange: 1.1,
    lastUpdated: "2026-03-17",
  },
  {
    id: "6",
    name: "Salbutamol 100mcg",
    manufacturer: "Cipla UK",
    stockStatus: "Low Stock",
    priceChange: -0.9,
    lastUpdated: "2026-03-16",
  },
  {
    id: "7",
    name: "Amlodipine 5mg",
    manufacturer: "Mylan Ltd",
    stockStatus: "In Stock",
    priceChange: 3.7,
    lastUpdated: "2026-03-17",
  },
  {
    id: "8",
    name: "Levothyroxine 50mcg",
    manufacturer: "Almus Pharma",
    stockStatus: "Low Stock",
    priceChange: -2.3,
    lastUpdated: "2026-03-14",
  },
  {
    id: "9",
    name: "Ramipril 5mg",
    manufacturer: "Accord Healthcare",
    stockStatus: "In Stock",
    priceChange: 0.0,
    lastUpdated: "2026-03-17",
  },
  {
    id: "10",
    name: "Clopidogrel 75mg",
    manufacturer: "Dr. Reddy's",
    stockStatus: "Out of Stock",
    priceChange: -6.1,
    lastUpdated: "2026-03-13",
  },
  {
    id: "11",
    name: "Aspirin 75mg",
    manufacturer: "Bayer plc",
    stockStatus: "In Stock",
    priceChange: 0.5,
    lastUpdated: "2026-03-17",
  },
  {
    id: "12",
    name: "Sertraline 50mg",
    manufacturer: "Milpharm Ltd",
    stockStatus: "Low Stock",
    priceChange: 1.2,
    lastUpdated: "2026-03-16",
  },
  {
    id: "13",
    name: "Ibuprofen 400mg",
    manufacturer: "Reckitt Benckiser",
    stockStatus: "In Stock",
    priceChange: -0.3,
    lastUpdated: "2026-03-17",
  },
  {
    id: "14",
    name: "Citalopram 20mg",
    manufacturer: "Actavis UK",
    stockStatus: "In Stock",
    priceChange: 0.8,
    lastUpdated: "2026-03-15",
  },
  {
    id: "15",
    name: "Lansoprazole 30mg",
    manufacturer: "Consilient Health",
    stockStatus: "Out of Stock",
    priceChange: 4.5,
    lastUpdated: "2026-03-14",
  },
  {
    id: "16",
    name: "Bisoprolol 2.5mg",
    manufacturer: "Kent Pharma",
    stockStatus: "In Stock",
    priceChange: -1.0,
    lastUpdated: "2026-03-17",
  },
  {
    id: "17",
    name: "Gabapentin 300mg",
    manufacturer: "Teva UK",
    stockStatus: "Low Stock",
    priceChange: 2.1,
    lastUpdated: "2026-03-16",
  },
  {
    id: "18",
    name: "Pregabalin 75mg",
    manufacturer: "Zentiva",
    stockStatus: "In Stock",
    priceChange: 0.2,
    lastUpdated: "2026-03-17",
  },
  {
    id: "19",
    name: "Simvastatin 20mg",
    manufacturer: "Accord Healthcare",
    stockStatus: "In Stock",
    priceChange: -0.5,
    lastUpdated: "2026-03-17",
  },
  {
    id: "20",
    name: "Fluoxetine 20mg",
    manufacturer: "Mylan Ltd",
    stockStatus: "Low Stock",
    priceChange: 1.7,
    lastUpdated: "2026-03-15",
  },
  {
    id: "21",
    name: "Diazepam 5mg",
    manufacturer: "Wockhardt UK",
    stockStatus: "Out of Stock",
    priceChange: -2.8,
    lastUpdated: "2026-03-13",
  },
  {
    id: "22",
    name: "Amoxicillin 250mg/5ml",
    manufacturer: "GSK Consumer",
    stockStatus: "In Stock",
    priceChange: 0.9,
    lastUpdated: "2026-03-17",
  },
  {
    id: "23",
    name: "Cefalexin 500mg",
    manufacturer: "Sandoz",
    stockStatus: "Low Stock",
    priceChange: 3.4,
    lastUpdated: "2026-03-16",
  },
  {
    id: "24",
    name: "Doxycycline 100mg",
    manufacturer: "Kent Pharma",
    stockStatus: "In Stock",
    priceChange: -1.5,
    lastUpdated: "2026-03-17",
  },
  {
    id: "25",
    name: "Erythromycin 250mg",
    manufacturer: "Abbott",
    stockStatus: "In Stock",
    priceChange: 0.0,
    lastUpdated: "2026-03-16",
  },
  {
    id: "26",
    name: "Clarithromycin 500mg",
    manufacturer: "Teva UK",
    stockStatus: "Out of Stock",
    priceChange: -3.2,
    lastUpdated: "2026-03-14",
  },
  {
    id: "27",
    name: "Naproxen 500mg",
    manufacturer: "Crescent Pharma",
    stockStatus: "In Stock",
    priceChange: 1.3,
    lastUpdated: "2026-03-17",
  },
  {
    id: "28",
    name: "Diclofenac 50mg",
    manufacturer: "Novartis",
    stockStatus: "Low Stock",
    priceChange: 2.7,
    lastUpdated: "2026-03-15",
  },
  {
    id: "29",
    name: "Codeine 30mg",
    manufacturer: "Zentiva",
    stockStatus: "In Stock",
    priceChange: -0.4,
    lastUpdated: "2026-03-17",
  },
  {
    id: "30",
    name: "Tramadol 50mg",
    manufacturer: "Mylan Ltd",
    stockStatus: "In Stock",
    priceChange: 0.6,
    lastUpdated: "2026-03-16",
  },
  {
    id: "31",
    name: "Paracetamol 500mg",
    manufacturer: "Accord Healthcare",
    stockStatus: "In Stock",
    priceChange: 0.1,
    lastUpdated: "2026-03-17",
  },
  {
    id: "32",
    name: "Morphine 10mg/5ml",
    manufacturer: "Wockhardt UK",
    stockStatus: "Out of Stock",
    priceChange: 5.2,
    lastUpdated: "2026-03-12",
  }
];

export const costSavingsData: ChartDataPoint[] = [
  { month: "Apr", savings: 180 },
  { month: "May", savings: 220 },
  { month: "Jun", savings: 195 },
  { month: "Jul", savings: 260 },
  { month: "Aug", savings: 240 },
  { month: "Sep", savings: 310 },
  { month: "Oct", savings: 290 },
  { month: "Nov", savings: 375 },
  { month: "Dec", savings: 340 },
  { month: "Jan", savings: 420 },
  { month: "Feb", savings: 395 },
  { month: "Mar", savings: 488 },
];
